var DEPARTEMENTS_ACTIFS = {
    "06": "Alpes-Maritimes", "13": "Bouches-du-Rhone", "17": "Charente-Maritime",
    "22": "Cotes-d-Armor", "30": "Gard", "31": "Haute-Garonne", "33": "Gironde",
    "34": "Herault", "35": "Ille-et-Vilaine", "44": "Loire-Atlantique",
    "49": "Maine-et-Loire", "50": "Manche", "54": "Meurthe-et-Moselle",
    "56": "Morbihan", "69": "Rhone", "74": "Haute-Savoie", "83": "Var", "85": "Vendee",
    "75": "Paris", "77": "Seine-et-Marne", "78": "Yvelines", "91": "Essonne",
    "92": "Hauts-de-Seine", "93": "Seine-Saint-Denis", "94": "Val-de-Marne", "95": "Val-d-Oise"
};

var REGIONS = {
    "nouvelle-aquitaine": { nom: "Nouvelle-Aquitaine", departements: ["17", "33"] },
    "pays-de-la-loire": { nom: "Pays de la Loire", departements: ["44", "49", "85"] },
    "bretagne": { nom: "Bretagne", departements: ["22", "35", "56"] },
    "occitanie": { nom: "Occitanie", departements: ["30", "31", "34"] },
    "provence-alpes-cote-d-azur": { nom: "Provence-Alpes-Cote d Azur", departements: ["06", "13", "83"] },
    "auvergne-rhone-alpes": { nom: "Auvergne-Rhone-Alpes", departements: ["69", "74"] },
    "normandie": { nom: "Normandie", departements: ["50"] },
    "grand-est": { nom: "Grand Est", departements: ["54"] },
    "ile-de-france": { nom: "Ile-de-France", departements: ["75", "77", "78", "91", "92", "93", "94", "95"] }
};

var CALLMEBOT = { phone: "33635084014", apikey: "9990329" };

function slugify(text) {
    return text.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-+|-+$/g, "");
}

async function getVillesDepartement(codeDep) {
    try {
        var response = await fetch("https://geo.api.gouv.fr/departements/" + codeDep + "/communes?fields=nom,code,codesPostaux");
        if (!response.ok) return [];
        return await response.json();
    } catch (error) { return []; }
}

async function validerLieu(recherche) {
    var slug = slugify(recherche);
    var rechercheClean = recherche.trim();
    if (DEPARTEMENTS_ACTIFS[rechercheClean]) {
        return { valide: true, type: "departement", code: rechercheClean, nom: DEPARTEMENTS_ACTIFS[rechercheClean], slug: rechercheClean };
    }
    for (var code in DEPARTEMENTS_ACTIFS) {
        if (slugify(DEPARTEMENTS_ACTIFS[code]) === slug) {
            return { valide: true, type: "departement", code: code, nom: DEPARTEMENTS_ACTIFS[code], slug: code };
        }
    }
    for (var regionSlug in REGIONS) {
        var regionData = REGIONS[regionSlug];
        if (slug === regionSlug || slug === slugify(regionData.nom)) {
            var depActifs = regionData.departements.filter(function(d) { return DEPARTEMENTS_ACTIFS[d]; });
            if (depActifs.length > 0) {
                return { valide: true, type: "region", code: regionSlug, nom: regionData.nom, slug: regionSlug, departements: depActifs };
            }
        }
    }
    for (var codeDep in DEPARTEMENTS_ACTIFS) {
        var villes = await getVillesDepartement(codeDep);
        for (var i = 0; i < villes.length; i++) {
            if (slugify(villes[i].nom) === slug) {
                return { valide: true, type: "ville", code: villes[i].code, nom: villes[i].nom, slug: slugify(villes[i].nom), departement: codeDep };
            }
        }
    }
    return { valide: false, raison: "lieu_non_trouve" };
}

function generateHTML(lieu, data, theme) {
    var nom = data.nom;
    var type = data.type;
    var prefix = "a ";
    if (type === "departement") prefix = "dans le ";
    if (type === "region") prefix = "en ";
    var titreComplet = prefix + nom;
    if (theme === "luxe") {
        return generateLuxeHTML(nom, titreComplet);
    }
    return generateSOSHTML(nom, titreComplet);
}

function generateSOSHTML(nom, titreComplet) {
    var TEL = "01 84 60 60 60";
    var TEL_CLEAN = TEL.replace(/\s/g, "");
    var MARQUE = "SOS Serrurier";
    var html = '<!DOCTYPE html><html lang="fr"><head>';
    html += '<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">';
    html += '<title>' + MARQUE + ' ' + nom + ' | URGENCE 24H/24 - Intervention 15min</title>';
    html += '<meta name="description" content="URGENCE Serrurier ' + titreComplet + '. Intervention en 15 minutes, 24h/24. Appelez le ' + TEL + '">';
    html += '<link rel="preconnect" href="https://fonts.googleapis.com">';
    html += '<link href="https://fonts.googleapis.com/css2?family=Oswald:wght@400;500;600;700&family=Open+Sans:wght@400;500;600;700&display=swap" rel="stylesheet">';
    html += '<style>';
    html += ':root{--red:#DC2626;--red-dark:#B91C1C;--red-light:#FEE2E2;--dark:#1F2937;--gray:#6B7280;--gray-light:#F9FAFB;--white:#FFFFFF}';
    html += '*{margin:0;padding:0;box-sizing:border-box}body{font-family:"Open Sans",sans-serif;color:var(--dark);background:var(--white)}h1,h2,h3,h4{font-family:"Oswald",sans-serif;font-weight:700}';
    html += '@keyframes pulse{0%,100%{transform:scale(1)}50%{transform:scale(1.05)}}@keyframes shake{0%,100%{transform:rotate(0)}25%{transform:rotate(-5deg)}75%{transform:rotate(5deg)}}@keyframes slideUp{from{opacity:0;transform:translateY(30px)}to{opacity:1;transform:translateY(0)}}@keyframes blink{0%,100%{opacity:1}50%{opacity:0.5}}';
    html += '.urgence-bar{background:var(--red);color:var(--white);padding:12px 0;animation:blink 2s infinite}.urgence-bar-inner{max-width:1200px;margin:0 auto;padding:0 20px;display:flex;justify-content:center;align-items:center;gap:15px;flex-wrap:wrap}.urgence-bar svg{width:24px;height:24px;fill:var(--white);animation:shake 0.5s infinite}.urgence-bar span{font-family:"Oswald",sans-serif;font-size:20px;letter-spacing:2px;text-transform:uppercase}';
    html += 'header{background:var(--white);box-shadow:0 4px 20px rgba(0,0,0,0.1);position:sticky;top:0;z-index:100}.header-inner{max-width:1200px;margin:0 auto;padding:15px 20px;display:flex;justify-content:space-between;align-items:center}.logo{display:flex;align-items:center;gap:12px;text-decoration:none}.logo-icon{width:55px;height:55px;background:var(--red);border-radius:12px;display:flex;align-items:center;justify-content:center}.logo-icon svg{width:32px;height:32px;fill:var(--white)}.logo-text{font-family:"Oswald",sans-serif;font-size:28px;color:var(--dark)}.logo-text span{color:var(--red)}.header-phone{display:flex;align-items:center;gap:10px;background:var(--red);color:var(--white);padding:15px 30px;border-radius:50px;text-decoration:none;font-weight:700;font-size:18px;animation:pulse 2s infinite}.header-phone:hover{background:var(--red-dark)}.header-phone svg{width:22px;height:22px;fill:var(--white)}';
    html += '.hero{background:linear-gradient(135deg,var(--gray-light) 0%,var(--white) 100%);padding:80px 0;position:relative;overflow:hidden}.hero::before{content:"";position:absolute;top:-50%;right:-20%;width:600px;height:600px;background:var(--red-light);border-radius:50%;opacity:0.5}.hero-inner{max-width:1200px;margin:0 auto;padding:0 20px;display:grid;grid-template-columns:1fr 1fr;gap:60px;align-items:center;position:relative;z-index:1}.hero-content{animation:slideUp 0.8s ease-out}.hero-badge{display:inline-flex;align-items:center;gap:8px;background:var(--red);color:var(--white);padding:10px 20px;border-radius:50px;font-size:14px;font-weight:600;margin-bottom:20px}.hero-badge .dot{width:10px;height:10px;background:var(--white);border-radius:50%;animation:blink 1s infinite}.hero h1{font-size:52px;line-height:1.1;margin-bottom:20px;color:var(--dark)}.hero h1 span{color:var(--red)}.hero-subtitle{font-size:20px;color:var(--gray);margin-bottom:30px;line-height:1.6}.hero-features{display:flex;flex-wrap:wrap;gap:15px;margin-bottom:35px}.hero-feature{display:flex;align-items:center;gap:8px;background:var(--white);padding:12px 20px;border-radius:10px;box-shadow:0 2px 10px rgba(0,0,0,0.08);font-weight:600;font-size:14px}.hero-feature svg{width:20px;height:20px;fill:var(--red)}.hero-buttons{display:flex;gap:15px;flex-wrap:wrap}.btn-urgence{display:inline-flex;align-items:center;gap:10px;background:var(--red);color:var(--white);padding:18px 40px;border-radius:12px;text-decoration:none;font-family:"Oswald",sans-serif;font-size:20px;letter-spacing:1px;transition:all 0.3s;animation:pulse 2s infinite}.btn-urgence:hover{background:var(--red-dark);transform:translateY(-3px)}.btn-urgence svg{width:24px;height:24px;fill:var(--white)}.btn-devis{display:inline-flex;align-items:center;gap:10px;background:var(--white);color:var(--red);padding:18px 40px;border-radius:12px;text-decoration:none;font-family:"Oswald",sans-serif;font-size:20px;letter-spacing:1px;border:3px solid var(--red);transition:all 0.3s}.btn-devis:hover{background:var(--red-light)}';
    html += '.trust-box{background:var(--white);border-radius:20px;padding:40px;box-shadow:0 20px 60px rgba(0,0,0,0.15);animation:slideUp 0.8s ease-out 0.2s both}.trust-header{text-align:center;margin-bottom:25px}.trust-header h3{font-size:24px;color:var(--dark);margin-bottom:10px}.trust-rating{display:flex;align-items:center;justify-content:center;gap:8px}.trust-stars{display:flex;gap:3px}.trust-stars svg{width:22px;height:22px;fill:#FBBF24}.trust-score{font-weight:700;font-size:18px;color:var(--dark)}.trust-reviews{color:var(--gray);font-size:14px}.trust-features{display:flex;flex-direction:column;gap:15px;margin-bottom:25px}.trust-feature{display:flex;align-items:center;gap:15px;padding:15px;background:var(--gray-light);border-radius:12px;border-left:4px solid var(--red)}.trust-feature svg{width:35px;height:35px;fill:var(--red);flex-shrink:0}.trust-feature h4{font-family:"Open Sans",sans-serif;font-size:16px;font-weight:700;color:var(--dark)}.trust-feature p{font-size:13px;color:var(--gray)}.trust-cta a{display:block;background:var(--red);color:var(--white);padding:18px;border-radius:12px;text-align:center;font-family:"Oswald",sans-serif;font-size:22px;text-decoration:none;animation:pulse 2s infinite}';
    html += '.assurances{padding:50px 0;background:var(--gray-light)}.assurances-inner{max-width:1200px;margin:0 auto;padding:0 20px}.assurances-title{text-align:center;font-size:14px;color:var(--gray);text-transform:uppercase;letter-spacing:2px;margin-bottom:25px}.assurances-logos{display:flex;justify-content:center;flex-wrap:wrap;gap:20px}.assurance-logo{background:var(--white);padding:15px 30px;border-radius:10px;font-weight:700;color:var(--dark);font-size:14px;box-shadow:0 2px 10px rgba(0,0,0,0.05)}';
    html += '.services{padding:80px 0;background:var(--white)}.container{max-width:1200px;margin:0 auto;padding:0 20px}.section-header{text-align:center;margin-bottom:50px}.section-header h2{font-size:42px;color:var(--dark);margin-bottom:15px}.section-header h2 span{color:var(--red)}.section-header p{font-size:18px;color:var(--gray)}.services-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:25px}.service-card{background:var(--white);border-radius:20px;padding:35px;text-align:center;border:2px solid var(--gray-light);transition:all 0.4s}.service-card:hover{border-color:var(--red);transform:translateY(-10px);box-shadow:0 20px 40px rgba(220,38,38,0.15)}.service-icon{width:80px;height:80px;background:linear-gradient(135deg,var(--red),var(--red-dark));border-radius:20px;display:flex;align-items:center;justify-content:center;margin:0 auto 20px}.service-icon svg{width:40px;height:40px;fill:var(--white)}.service-card h3{font-size:22px;color:var(--dark);margin-bottom:12px}.service-card p{color:var(--gray);font-size:15px;line-height:1.6;margin-bottom:20px}.service-price{display:inline-block;background:var(--red-light);color:var(--red);padding:10px 25px;border-radius:50px;font-weight:700}';
    html += '.avis{padding:80px 0;background:var(--gray-light)}.avis-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:25px}.avis-card{background:var(--white);border-radius:20px;padding:30px;box-shadow:0 5px 20px rgba(0,0,0,0.05)}.avis-stars{display:flex;gap:4px;margin-bottom:15px}.avis-stars svg{width:20px;height:20px;fill:#FBBF24}.avis-text{font-size:15px;line-height:1.7;color:var(--dark);margin-bottom:20px}.avis-author{display:flex;align-items:center;gap:12px}.avis-avatar{width:45px;height:45px;background:var(--red);color:var(--white);border-radius:50%;display:flex;align-items:center;justify-content:center;font-weight:700}.avis-info h4{font-size:15px;font-weight:700;color:var(--dark)}.avis-info p{font-size:13px;color:var(--gray)}';
    html += '.contact{padding:80px 0;background:var(--white)}.contact-grid{display:grid;grid-template-columns:1fr 1fr;gap:50px;align-items:start}.contact-info h3{font-size:36px;color:var(--dark);margin-bottom:20px}.contact-info h3 span{color:var(--red)}.contact-info>p{color:var(--gray);font-size:17px;line-height:1.7;margin-bottom:30px}.contact-methods{display:flex;flex-direction:column;gap:15px}.contact-method{display:flex;align-items:center;gap:15px;padding:20px;background:var(--gray-light);border-radius:15px}.contact-method svg{width:35px;height:35px;fill:var(--red)}.contact-method h4{font-family:"Open Sans",sans-serif;font-size:14px;font-weight:600;color:var(--gray);margin-bottom:3px}.contact-method a{color:var(--red);font-size:20px;font-weight:700;text-decoration:none}.contact-method span{color:var(--dark);font-size:15px}';
    html += '.form-box{background:var(--white);border-radius:20px;padding:40px;box-shadow:0 10px 40px rgba(0,0,0,0.1);border:2px solid var(--gray-light)}.form-box h3{font-size:28px;color:var(--dark);margin-bottom:25px;text-align:center}.form-group{margin-bottom:20px}.form-group label{display:block;font-weight:600;margin-bottom:8px;font-size:14px;color:var(--dark)}.form-group input,.form-group select{width:100%;padding:15px;background:var(--gray-light);border:2px solid transparent;border-radius:10px;font-size:16px;transition:all 0.3s}.form-group input:focus,.form-group select:focus{outline:none;border-color:var(--red);background:var(--white)}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:15px}.btn-submit{width:100%;padding:18px;background:var(--red);color:var(--white);border:none;border-radius:10px;font-family:"Oswald",sans-serif;font-size:20px;cursor:pointer;transition:all 0.3s}.btn-submit:hover{background:var(--red-dark)}.success-message{display:none;text-align:center;padding:40px}.success-message.show{display:block}.success-icon{width:70px;height:70px;background:var(--red);border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto 20px}.success-icon svg{width:35px;height:35px;fill:var(--white)}.success-message h4{font-size:24px;color:var(--dark);margin-bottom:10px}.success-message p{color:var(--gray)}';
    html += '.cta{padding:80px 0;background:linear-gradient(135deg,var(--red),var(--red-dark));text-align:center}.cta h2{font-size:42px;color:var(--white);margin-bottom:15px}.cta p{font-size:20px;color:rgba(255,255,255,0.9);margin-bottom:30px}.cta-phone{display:inline-flex;align-items:center;gap:15px;background:var(--white);color:var(--red);padding:20px 50px;border-radius:15px;text-decoration:none;font-family:"Oswald",sans-serif;font-size:32px;animation:pulse 2s infinite}.cta-phone svg{width:32px;height:32px;fill:var(--red)}';
    html += 'footer{padding:40px 0;background:var(--dark);text-align:center}footer p{color:rgba(255,255,255,0.7);font-size:14px}';
    html += '.floating-btn{position:fixed;bottom:25px;right:25px;width:65px;height:65px;background:var(--red);border-radius:50%;display:flex;align-items:center;justify-content:center;text-decoration:none;box-shadow:0 5px 25px rgba(220,38,38,0.4);z-index:1000;animation:pulse 2s infinite}.floating-btn svg{width:30px;height:30px;fill:var(--white)}';
    html += '@media(max-width:1024px){.hero-inner,.contact-grid{grid-template-columns:1fr}.services-grid,.avis-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:768px){.hero h1{font-size:36px}.services-grid,.avis-grid{grid-template-columns:1fr}.form-row{grid-template-columns:1fr}.header-phone span{display:none}}';
    html += '</style></head><body>';
    html += '<svg xmlns="http://www.w3.org/2000/svg" style="display:none"><symbol id="i-alert" viewBox="0 0 24 24"><path d="M12 2L1 21h22L12 2zm0 3.99L19.53 19H4.47L12 5.99zM11 16h2v2h-2zm0-6h2v4h-2z"/></symbol><symbol id="i-phone" viewBox="0 0 24 24"><path d="M6.62 10.79c1.44 2.83 3.76 5.14 6.59 6.59l2.2-2.2c.27-.27.67-.36 1.02-.24 1.12.37 2.33.57 3.57.57.55 0 1 .45 1 1V20c0 .55-.45 1-1 1-9.39 0-17-7.61-17-17 0-.55.45-1 1-1h3.5c.55 0 1 .45 1 1 0 1.25.2 2.45.57 3.57.11.35.03.74-.25 1.02l-2.2 2.2z"/></symbol><symbol id="i-clock" viewBox="0 0 24 24"><path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10 10-4.5 10-10S17.5 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm.5-13H11v6l5.25 3.15.75-1.23-4.5-2.67z"/></symbol><symbol id="i-bolt" viewBox="0 0 24 24"><path d="M7 2v11h3v9l7-12h-4l4-8z"/></symbol><symbol id="i-shield" viewBox="0 0 24 24"><path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4z"/></symbol><symbol id="i-check" viewBox="0 0 24 24"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></symbol><symbol id="i-lock" viewBox="0 0 24 24"><path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm-6 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm3.1-9H8.9V6c0-1.71 1.39-3.1 3.1-3.1 1.71 0 3.1 1.39 3.1 3.1v2z"/></symbol><symbol id="i-door" viewBox="0 0 24 24"><path d="M19 19V5c0-1.1-.9-2-2-2H7c-1.1 0-2 .9-2 2v14H3v2h18v-2h-2zm-2 0H7V5h10v14zm-4-8c.55 0 1-.45 1-1s-.45-1-1-1-1 .45-1 1 .45 1 1 1z"/></symbol><symbol id="i-key" viewBox="0 0 24 24"><path d="M12.65 10C11.83 7.67 9.61 6 7 6c-3.31 0-6 2.69-6 6s2.69 6 6 6c2.61 0 4.83-1.67 5.65-4H17v4h4v-4h2v-4H12.65zM7 14c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2z"/></symbol><symbol id="i-tool" viewBox="0 0 24 24"><path d="M22.7 19l-9.1-9.1c.9-2.3.4-5-1.5-6.9-2-2-5-2.4-7.4-1.3L9 6 6 9 1.6 4.7C.4 7.1.9 10.1 2.9 12.1c1.9 1.9 4.6 2.4 6.9 1.5l9.1 9.1c.4.4 1 .4 1.4 0l2.3-2.3c.5-.4.5-1.1.1-1.4z"/></symbol><symbol id="i-home" viewBox="0 0 24 24"><path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z"/></symbol><symbol id="i-star" viewBox="0 0 24 24"><path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z"/></symbol><symbol id="i-location" viewBox="0 0 24 24"><path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"/></symbol><symbol id="i-euro" viewBox="0 0 24 24"><path d="M15 18.5c-2.51 0-4.68-1.42-5.76-3.5H15v-2H8.58c-.05-.33-.08-.66-.08-1s.03-.67.08-1H15V9H9.24C10.32 6.92 12.5 5.5 15 5.5c1.61 0 3.09.59 4.23 1.57L21 5.3C19.41 3.87 17.3 3 15 3c-3.92 0-7.24 2.51-8.48 6H3v2h3.06c-.04.33-.06.66-.06 1s.02.67.06 1H3v2h3.52c1.24 3.49 4.56 6 8.48 6 2.31 0 4.41-.87 6-2.3l-1.78-1.77c-1.13.98-2.6 1.57-4.22 1.57z"/></symbol></svg>';
    html += '<div class="urgence-bar"><div class="urgence-bar-inner"><svg><use href="#i-alert"/></svg><span>URGENCE SERRURIER - INTERVENTION 24H/24 ET 7J/7</span><svg><use href="#i-alert"/></svg></div></div>';
    html += '<header><div class="header-inner"><a href="/" class="logo"><div class="logo-icon"><svg><use href="#i-lock"/></svg></div><div class="logo-text"><span>SOS</span> Serrurier</div></a><a href="tel:' + TEL_CLEAN + '" class="header-phone"><svg><use href="#i-phone"/></svg> <span>' + TEL + '</span></a></div></header>';
    html += '<section class="hero"><div class="hero-inner"><div class="hero-content"><div class="hero-badge"><span class="dot"></span> Serrurier disponible maintenant</div><h1>SERRURIER <span>' + nom.toUpperCase() + '</span></h1><p class="hero-subtitle">Intervention URGENTE en 15 minutes ' + titreComplet + '. Ouverture de porte, changement de serrure, depannage 24h/24. Devis gratuit sur place.</p><div class="hero-features"><div class="hero-feature"><svg><use href="#i-bolt"/></svg> 15 min chrono</div><div class="hero-feature"><svg><use href="#i-shield"/></svg> Agree assurance</div><div class="hero-feature"><svg><use href="#i-euro"/></svg> Devis gratuit</div><div class="hero-feature"><svg><use href="#i-clock"/></svg> 24h/24 - 7j/7</div></div><div class="hero-buttons"><a href="tel:' + TEL_CLEAN + '" class="btn-urgence"><svg><use href="#i-phone"/></svg> APPELER MAINTENANT</a><a href="#contact" class="btn-devis">Devis gratuit</a></div></div>';
    html += '<div class="trust-box"><div class="trust-header"><h3>Pourquoi nous choisir ?</h3><div class="trust-rating"><div class="trust-stars"><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg></div><span class="trust-score">4.9/5</span><span class="trust-reviews">(2 847 avis)</span></div></div><div class="trust-features"><div class="trust-feature"><svg><use href="#i-bolt"/></svg><div><h4>Intervention express</h4><p>Sur place en 15 minutes</p></div></div><div class="trust-feature"><svg><use href="#i-euro"/></svg><div><h4>Prix fixes</h4><p>Devis gratuit avant intervention</p></div></div><div class="trust-feature"><svg><use href="#i-shield"/></svg><div><h4>Agree assurances</h4><p>Prise en charge facilitee</p></div></div></div><div class="trust-cta"><a href="tel:' + TEL_CLEAN + '"><svg><use href="#i-phone"/></svg> ' + TEL + '</a></div></div></div></section>';
    html += '<section class="assurances"><div class="assurances-inner"><div class="assurances-title">Agree par toutes les assurances</div><div class="assurances-logos"><div class="assurance-logo">AXA</div><div class="assurance-logo">MAIF</div><div class="assurance-logo">Groupama</div><div class="assurance-logo">MACIF</div><div class="assurance-logo">Allianz</div><div class="assurance-logo">Generali</div></div></div></section>';
    html += '<section class="services"><div class="container"><div class="section-header"><h2>NOS SERVICES <span>D\'URGENCE</span></h2><p>Intervention rapide pour tous vos problemes de serrurerie</p></div><div class="services-grid"><div class="service-card"><div class="service-icon"><svg><use href="#i-door"/></svg></div><h3>OUVERTURE DE PORTE</h3><p>Porte claquee ou cle perdue. Ouverture sans degat en 15 minutes.</p><span class="service-price">Des 89 EUR</span></div><div class="service-card"><div class="service-icon"><svg><use href="#i-lock"/></svg></div><h3>CHANGEMENT SERRURE</h3><p>Remplacement rapide toutes marques. Serrures 3 et 5 points.</p><span class="service-price">Des 129 EUR</span></div><div class="service-card"><div class="service-icon"><svg><use href="#i-shield"/></svg></div><h3>BLINDAGE PORTE</h3><p>Securisation complete avec solutions certifiees A2P.</p><span class="service-price">Des 890 EUR</span></div><div class="service-card"><div class="service-icon"><svg><use href="#i-key"/></svg></div><h3>DOUBLE DE CLES</h3><p>Reproduction immediate de cles classiques et securisees.</p><span class="service-price">Des 15 EUR</span></div><div class="service-card"><div class="service-icon"><svg><use href="#i-home"/></svg></div><h3>INSTALLATION</h3><p>Pose de serrures connectees et haute securite.</p><span class="service-price">Des 149 EUR</span></div><div class="service-card"><div class="service-icon"><svg><use href="#i-tool"/></svg></div><h3>DEPANNAGE URGENT</h3><p>Intervention 24h/24 pour toutes urgences.</p><span class="service-price">Des 99 EUR</span></div></div></div></section>';
    html += '<section class="avis"><div class="container"><div class="section-header"><h2>AVIS <span>CLIENTS</span></h2><p>Ce que nos clients disent de nous</p></div><div class="avis-grid"><div class="avis-card"><div class="avis-stars"><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg></div><p class="avis-text">"Intervention ultra rapide ! Le serrurier est arrive en 15 minutes. Porte ouverte sans aucun degat. Prix annonce respecte. Je recommande !"</p><div class="avis-author"><div class="avis-avatar">M</div><div class="avis-info"><h4>Marie D.</h4><p>' + nom + '</p></div></div></div><div class="avis-card"><div class="avis-stars"><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg></div><p class="avis-text">"Bloque dehors un dimanche soir a 23h. Ils ont repondu immediatement et le serrurier etait la en 20 minutes. Service impeccable !"</p><div class="avis-author"><div class="avis-avatar">P</div><div class="avis-info"><h4>Pierre L.</h4><p>' + nom + '</p></div></div></div><div class="avis-card"><div class="avis-stars"><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg></div><p class="avis-text">"Changement de serrure apres cambriolage. Equipe rassurante, travail propre et rapide. Facture prise en charge par l\'assurance."</p><div class="avis-author"><div class="avis-avatar">S</div><div class="avis-info"><h4>Sophie M.</h4><p>' + nom + '</p></div></div></div></div></div></section>';
    html += '<section class="contact" id="contact"><div class="container"><div class="section-header"><h2>CONTACTEZ-<span>NOUS</span></h2><p>Demandez un devis gratuit ou une intervention immediate</p></div><div class="contact-grid"><div class="contact-info"><h3>BESOIN D\'UN <span>SERRURIER ?</span></h3><p>Notre equipe est disponible 24h/24 et 7j/7 pour repondre a toutes vos urgences de serrurerie ' + titreComplet + '.</p><div class="contact-methods"><div class="contact-method"><svg><use href="#i-phone"/></svg><div><h4>Par telephone</h4><a href="tel:' + TEL_CLEAN + '">' + TEL + '</a></div></div><div class="contact-method"><svg><use href="#i-clock"/></svg><div><h4>Disponibilite</h4><span>24h/24 - 7j/7 - Jours feries</span></div></div><div class="contact-method"><svg><use href="#i-location"/></svg><div><h4>Zone d\'intervention</h4><span>' + nom + ' et environs</span></div></div></div></div>';
    html += '<div class="form-box"><div id="formContainer"><h3>DEMANDE DE DEVIS GRATUIT</h3><form id="contactForm"><div class="form-row"><div class="form-group"><label>Nom *</label><input type="text" id="nom" required placeholder="Votre nom"></div><div class="form-group"><label>Telephone *</label><input type="tel" id="telephone" required placeholder="06 12 34 56 78"></div></div><div class="form-group"><label>Adresse *</label><input type="text" id="adresse" required placeholder="Adresse d\'intervention"></div><div class="form-group"><label>Type de probleme *</label><select id="probleme" required><option value="">Selectionnez</option><option>Porte claquee</option><option>Cle perdue</option><option>Cle cassee</option><option>Serrure bloquee</option><option>Cambriolage</option><option>Changement serrure</option><option>Autre</option></select></div><div class="form-group"><label>Urgence *</label><select id="urgence" required><option value="">Selectionnez</option><option>URGENT - Maintenant</option><option>Dans l\'heure</option><option>Aujourd\'hui</option><option>Prochains jours</option></select></div><button type="submit" class="btn-submit">ENVOYER MA DEMANDE</button></form></div><div class="success-message" id="successMessage"><div class="success-icon"><svg><use href="#i-check"/></svg></div><h4>Demande envoyee !</h4><p>Un serrurier vous rappelle dans les 5 minutes.</p></div></div></div></div></section>';
    html += '<section class="cta"><div class="container"><h2>URGENCE SERRURIER ?</h2><p>Appelez maintenant - Intervention en 15 minutes</p><a href="tel:' + TEL_CLEAN + '" class="cta-phone"><svg><use href="#i-phone"/></svg> ' + TEL + '</a></div></section>';
    html += '<footer><div class="container"><p>2025 ' + MARQUE + ' - Serrurier ' + nom + ' - Tous droits reserves</p></div></footer>';
    html += '<a href="tel:' + TEL_CLEAN + '" class="floating-btn"><svg><use href="#i-phone"/></svg></a>';
    html += '<script>var CALLMEBOT_PHONE="33635084014",CALLMEBOT_APIKEY="9990329",LIEU="' + nom + '",MARQUE="' + MARQUE + '";document.getElementById("contactForm").addEventListener("submit",function(e){e.preventDefault();var d={nom:document.getElementById("nom").value,telephone:document.getElementById("telephone").value,adresse:document.getElementById("adresse").value,probleme:document.getElementById("probleme").value,urgence:document.getElementById("urgence").value};var m="*NOUVEAU CONTACT*%0A%0A*Marque:* "+MARQUE+"%0A*Page:* Serrurier "+LIEU+"%0A*Nom:* "+d.nom+"%0A*Tel:* "+d.telephone+"%0A*Adresse:* "+d.adresse+"%0A*Probleme:* "+d.probleme+"%0A*Urgence:* "+d.urgence;try{fetch("https://api.callmebot.com/whatsapp.php?phone="+CALLMEBOT_PHONE+"&text="+m+"&apikey="+CALLMEBOT_APIKEY,{method:"GET",mode:"no-cors"})}catch(err){}document.getElementById("formContainer").style.display="none";document.getElementById("successMessage").classList.add("show")});document.querySelectorAll(\'a[href^="#"]\').forEach(function(a){a.addEventListener("click",function(e){e.preventDefault();var t=document.querySelector(this.getAttribute("href"));if(t)t.scrollIntoView({behavior:"smooth"})})});</script>';
    html += '</body></html>';
    return html;
}

function generateLuxeHTML(nom, titreComplet) {
    var TEL = "01 80 00 00 00";
    var TEL_CLEAN = TEL.replace(/\s/g, "");
    var MARQUE = "Maison Secure";
    var html = '<!DOCTYPE html><html lang="fr"><head>';
    html += '<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">';
    html += '<title>' + MARQUE + ' ' + nom + ' | Serrurier Premium - Excellence et Securite</title>';
    html += '<meta name="description" content="' + MARQUE + ' - Serrurier haut de gamme ' + titreComplet + '. Service premium 24h/24.">';
    html += '<link rel="preconnect" href="https://fonts.googleapis.com">';
    html += '<link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;500;600;700&family=Lato:wght@300;400;500;700&display=swap" rel="stylesheet">';
    html += '<style>';
    html += ':root{--gold:#D4A853;--gold-dark:#B8922E;--gold-light:#F5ECD7;--navy:#1E3A5F;--navy-dark:#0F2744;--cream:#FFFDF7;--white:#FFFFFF;--gray:#64748B;--gray-light:#F8FAFC}';
    html += '*{margin:0;padding:0;box-sizing:border-box}body{font-family:"Lato",sans-serif;color:var(--navy);background:var(--cream)}h1,h2,h3,h4{font-family:"Playfair Display",serif;font-weight:600}';
    html += '@keyframes fadeIn{from{opacity:0;transform:translateY(20px)}to{opacity:1;transform:translateY(0)}}@keyframes float{0%,100%{transform:translateY(0)}50%{transform:translateY(-10px)}}';
    html += '.top-bar{background:var(--navy);color:var(--white);padding:12px 0}.top-bar-inner{max-width:1200px;margin:0 auto;padding:0 20px;display:flex;justify-content:center;align-items:center;gap:30px;flex-wrap:wrap}.top-bar-item{display:flex;align-items:center;gap:8px;font-size:14px;letter-spacing:0.5px}.top-bar-item svg{width:18px;height:18px;fill:var(--gold)}';
    html += 'header{background:var(--white);box-shadow:0 2px 30px rgba(0,0,0,0.06);position:sticky;top:0;z-index:100}.header-inner{max-width:1200px;margin:0 auto;padding:20px;display:flex;justify-content:space-between;align-items:center}.logo{display:flex;align-items:center;gap:15px;text-decoration:none}.logo-icon{width:55px;height:55px;background:linear-gradient(135deg,var(--gold),var(--gold-dark));border-radius:50%;display:flex;align-items:center;justify-content:center;box-shadow:0 4px 15px rgba(212,168,83,0.3)}.logo-icon svg{width:28px;height:28px;fill:var(--white)}.logo-text{font-family:"Playfair Display",serif;font-size:26px;color:var(--navy)}.logo-text span{color:var(--gold)}.logo-sub{font-size:11px;color:var(--gray);letter-spacing:3px;text-transform:uppercase}.header-contact{display:flex;align-items:center;gap:20px}.header-phone{display:flex;align-items:center;gap:10px;color:var(--navy);text-decoration:none;font-weight:500}.header-phone svg{width:20px;height:20px;fill:var(--gold)}.btn-rdv{background:linear-gradient(135deg,var(--gold),var(--gold-dark));color:var(--white);padding:14px 30px;border-radius:50px;text-decoration:none;font-weight:600;font-size:14px;letter-spacing:1px;text-transform:uppercase;transition:all 0.3s;box-shadow:0 4px 15px rgba(212,168,83,0.3)}.btn-rdv:hover{transform:translateY(-2px);box-shadow:0 6px 25px rgba(212,168,83,0.4)}';
    html += '.hero{background:linear-gradient(180deg,var(--white) 0%,var(--cream) 100%);padding:100px 0;position:relative;overflow:hidden}.hero::before{content:"";position:absolute;top:0;right:0;width:50%;height:100%;background:linear-gradient(135deg,var(--gold-light) 0%,transparent 70%);opacity:0.5}.hero-inner{max-width:1200px;margin:0 auto;padding:0 20px;display:grid;grid-template-columns:1fr 1fr;gap:80px;align-items:center;position:relative;z-index:1}.hero-content{animation:fadeIn 1s ease-out}.hero-badge{display:inline-flex;align-items:center;gap:10px;background:var(--gold-light);color:var(--gold-dark);padding:10px 25px;border-radius:50px;font-size:13px;font-weight:600;letter-spacing:1px;text-transform:uppercase;margin-bottom:25px}.hero h1{font-size:48px;line-height:1.2;margin-bottom:25px;color:var(--navy)}.hero h1 span{color:var(--gold);font-style:italic}.hero-subtitle{font-size:18px;color:var(--gray);margin-bottom:35px;line-height:1.8;font-weight:300}.hero-features{display:flex;gap:30px;margin-bottom:40px}.hero-feature{text-align:center}.hero-feature-icon{width:60px;height:60px;background:var(--white);border:2px solid var(--gold-light);border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto 12px;transition:all 0.3s}.hero-feature-icon svg{width:28px;height:28px;fill:var(--gold)}.hero-feature:hover .hero-feature-icon{background:var(--gold);border-color:var(--gold)}.hero-feature:hover .hero-feature-icon svg{fill:var(--white)}.hero-feature span{font-size:13px;color:var(--navy);font-weight:500}.hero-buttons{display:flex;gap:20px}.btn-primary{display:inline-flex;align-items:center;gap:10px;background:linear-gradient(135deg,var(--gold),var(--gold-dark));color:var(--white);padding:18px 40px;border-radius:50px;text-decoration:none;font-weight:600;font-size:15px;letter-spacing:1px;transition:all 0.3s;box-shadow:0 4px 20px rgba(212,168,83,0.3)}.btn-primary:hover{transform:translateY(-3px);box-shadow:0 8px 30px rgba(212,168,83,0.4)}.btn-primary svg{width:20px;height:20px;fill:var(--white)}.btn-secondary{display:inline-flex;align-items:center;gap:10px;background:var(--white);color:var(--navy);padding:18px 40px;border-radius:50px;text-decoration:none;font-weight:600;font-size:15px;letter-spacing:1px;border:2px solid var(--navy);transition:all 0.3s}.btn-secondary:hover{background:var(--navy);color:var(--white)}';
    html += '.trust-box{background:var(--white);border-radius:30px;padding:45px;box-shadow:0 20px 60px rgba(0,0,0,0.08);animation:fadeIn 1s ease-out 0.3s both}.trust-box-header{text-align:center;margin-bottom:30px;padding-bottom:25px;border-bottom:1px solid var(--gold-light)}.trust-box-header h3{font-size:24px;color:var(--navy);margin-bottom:15px}.trust-rating{display:flex;align-items:center;justify-content:center;gap:10px}.trust-stars{display:flex;gap:3px}.trust-stars svg{width:20px;height:20px;fill:var(--gold)}.trust-score{font-weight:700;color:var(--navy)}.trust-reviews{color:var(--gray);font-size:14px}.trust-features{display:flex;flex-direction:column;gap:20px;margin-bottom:30px}.trust-feature{display:flex;align-items:center;gap:18px;padding:18px;background:var(--cream);border-radius:15px}.trust-feature svg{width:35px;height:35px;fill:var(--gold);flex-shrink:0}.trust-feature h4{font-family:"Lato",sans-serif;font-size:15px;font-weight:700;color:var(--navy);margin-bottom:3px}.trust-feature p{font-size:13px;color:var(--gray)}.trust-cta{text-align:center}.trust-cta a{display:block;background:linear-gradient(135deg,var(--gold),var(--gold-dark));color:var(--white);padding:18px;border-radius:15px;font-size:18px;font-weight:600;text-decoration:none;letter-spacing:1px}.trust-cta p{margin-top:12px;font-size:12px;color:var(--gray)}';
    html += '.services{padding:100px 0;background:var(--white)}.container{max-width:1200px;margin:0 auto;padding:0 20px}.section-header{text-align:center;margin-bottom:60px}.section-label{display:inline-block;background:var(--gold-light);color:var(--gold-dark);padding:8px 20px;border-radius:50px;font-size:12px;font-weight:600;letter-spacing:2px;text-transform:uppercase;margin-bottom:20px}.section-header h2{font-size:42px;color:var(--navy);margin-bottom:15px}.section-header p{font-size:18px;color:var(--gray);font-weight:300}.services-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:30px}.service-card{background:var(--cream);border-radius:25px;padding:40px 30px;text-align:center;transition:all 0.4s;border:2px solid transparent}.service-card:hover{background:var(--white);border-color:var(--gold);transform:translateY(-10px);box-shadow:0 20px 50px rgba(212,168,83,0.15)}.service-icon{width:85px;height:85px;background:linear-gradient(135deg,var(--gold),var(--gold-dark));border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto 25px;box-shadow:0 8px 25px rgba(212,168,83,0.25)}.service-icon svg{width:40px;height:40px;fill:var(--white)}.service-card h3{font-size:22px;color:var(--navy);margin-bottom:15px}.service-card p{color:var(--gray);font-size:15px;line-height:1.7;margin-bottom:20px;font-weight:300}.service-price{display:inline-block;background:var(--white);color:var(--gold-dark);padding:10px 25px;border-radius:50px;font-weight:700;border:1px solid var(--gold)}';
    html += '.avis{padding:100px 0;background:var(--cream)}.avis-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:30px}.avis-card{background:var(--white);border-radius:25px;padding:35px;box-shadow:0 10px 30px rgba(0,0,0,0.04)}.avis-header{display:flex;align-items:center;gap:15px;margin-bottom:20px}.avis-avatar{width:55px;height:55px;background:linear-gradient(135deg,var(--gold),var(--gold-dark));color:var(--white);border-radius:50%;display:flex;align-items:center;justify-content:center;font-family:"Playfair Display",serif;font-size:22px}.avis-info h4{font-family:"Lato",sans-serif;font-size:16px;font-weight:700;color:var(--navy)}.avis-info p{font-size:13px;color:var(--gray)}.avis-stars{display:flex;gap:3px;margin-bottom:15px}.avis-stars svg{width:18px;height:18px;fill:var(--gold)}.avis-text{font-size:15px;line-height:1.8;color:var(--navy);font-style:italic;font-weight:300}';
    html += '.contact{padding:100px 0;background:var(--white)}.contact-grid{display:grid;grid-template-columns:1fr 1fr;gap:60px;align-items:start}.contact-info h3{font-size:38px;color:var(--navy);margin-bottom:20px}.contact-info h3 span{color:var(--gold)}.contact-info>p{color:var(--gray);font-size:17px;line-height:1.8;margin-bottom:35px;font-weight:300}.contact-methods{display:flex;flex-direction:column;gap:20px}.contact-method{display:flex;align-items:center;gap:20px;padding:25px;background:var(--cream);border-radius:20px}.contact-method svg{width:30px;height:30px;fill:var(--gold)}.contact-method h4{font-family:"Lato",sans-serif;font-size:13px;font-weight:600;color:var(--gray);text-transform:uppercase;letter-spacing:1px;margin-bottom:5px}.contact-method a{color:var(--navy);font-size:20px;font-weight:700;text-decoration:none}.contact-method span{color:var(--navy);font-size:16px}';
    html += '.form-box{background:var(--cream);border-radius:30px;padding:45px;border:1px solid var(--gold-light)}.form-box h3{font-size:28px;color:var(--navy);margin-bottom:10px;text-align:center}.form-box>p{text-align:center;color:var(--gray);margin-bottom:30px;font-size:15px}.form-group{margin-bottom:22px}.form-group label{display:block;font-weight:600;margin-bottom:10px;font-size:13px;color:var(--navy);text-transform:uppercase;letter-spacing:1px}.form-group input,.form-group select{width:100%;padding:16px 20px;background:var(--white);border:1px solid var(--gold-light);border-radius:12px;font-size:16px;color:var(--navy);transition:all 0.3s}.form-group input:focus,.form-group select:focus{outline:none;border-color:var(--gold);box-shadow:0 0 0 3px rgba(212,168,83,0.1)}.form-row{display:grid;grid-template-columns:1fr 1fr;gap:20px}.btn-submit{width:100%;padding:18px;background:linear-gradient(135deg,var(--gold),var(--gold-dark));color:var(--white);border:none;border-radius:12px;font-size:16px;font-weight:600;cursor:pointer;letter-spacing:1px;text-transform:uppercase;transition:all 0.3s}.btn-submit:hover{transform:translateY(-2px);box-shadow:0 8px 25px rgba(212,168,83,0.3)}.success-message{display:none;text-align:center;padding:50px}.success-message.show{display:block}.success-icon{width:80px;height:80px;background:linear-gradient(135deg,var(--gold),var(--gold-dark));border-radius:50%;display:flex;align-items:center;justify-content:center;margin:0 auto 25px}.success-icon svg{width:40px;height:40px;fill:var(--white)}.success-message h4{font-size:26px;color:var(--navy);margin-bottom:10px}.success-message p{color:var(--gray);font-size:16px}';
    html += '.cta{padding:100px 0;background:linear-gradient(135deg,var(--navy),var(--navy-dark));text-align:center;position:relative;overflow:hidden}.cta-content{position:relative;z-index:1}.cta h2{font-size:42px;color:var(--white);margin-bottom:15px}.cta p{font-size:18px;color:rgba(255,255,255,0.8);margin-bottom:35px;font-weight:300}.cta-phone{display:inline-flex;align-items:center;gap:15px;background:linear-gradient(135deg,var(--gold),var(--gold-dark));color:var(--white);padding:22px 55px;border-radius:60px;text-decoration:none;font-family:"Playfair Display",serif;font-size:30px;box-shadow:0 10px 40px rgba(212,168,83,0.4)}.cta-phone svg{width:30px;height:30px;fill:var(--white)}';
    html += 'footer{padding:50px 0;background:var(--navy-dark);text-align:center}footer p{color:rgba(255,255,255,0.6);font-size:14px}';
    html += '.floating-btn{position:fixed;bottom:30px;right:30px;width:65px;height:65px;background:linear-gradient(135deg,var(--gold),var(--gold-dark));border-radius:50%;display:flex;align-items:center;justify-content:center;text-decoration:none;box-shadow:0 8px 30px rgba(212,168,83,0.4);z-index:1000;animation:float 3s ease-in-out infinite}.floating-btn svg{width:28px;height:28px;fill:var(--white)}';
    html += '@media(max-width:1024px){.hero-inner,.contact-grid{grid-template-columns:1fr}.services-grid,.avis-grid{grid-template-columns:repeat(2,1fr)}}@media(max-width:768px){.hero h1{font-size:36px}.services-grid,.avis-grid{grid-template-columns:1fr}.form-row{grid-template-columns:1fr}.hero-features{flex-direction:column;align-items:flex-start;gap:15px}}';
    html += '</style></head><body>';
    html += '<svg xmlns="http://www.w3.org/2000/svg" style="display:none"><symbol id="i-phone" viewBox="0 0 24 24"><path d="M6.62 10.79c1.44 2.83 3.76 5.14 6.59 6.59l2.2-2.2c.27-.27.67-.36 1.02-.24 1.12.37 2.33.57 3.57.57.55 0 1 .45 1 1V20c0 .55-.45 1-1 1-9.39 0-17-7.61-17-17 0-.55.45-1 1-1h3.5c.55 0 1 .45 1 1 0 1.25.2 2.45.57 3.57.11.35.03.74-.25 1.02l-2.2 2.2z"/></symbol><symbol id="i-clock" viewBox="0 0 24 24"><path d="M12 2C6.5 2 2 6.5 2 12s4.5 10 10 10 10-4.5 10-10S17.5 2 12 2zm0 18c-4.41 0-8-3.59-8-8s3.59-8 8-8 8 3.59 8 8-3.59 8-8 8zm.5-13H11v6l5.25 3.15.75-1.23-4.5-2.67z"/></symbol><symbol id="i-shield" viewBox="0 0 24 24"><path d="M12 1L3 5v6c0 5.55 3.84 10.74 9 12 5.16-1.26 9-6.45 9-12V5l-9-4z"/></symbol><symbol id="i-check" viewBox="0 0 24 24"><path d="M9 16.17L4.83 12l-1.42 1.41L9 19 21 7l-1.41-1.41z"/></symbol><symbol id="i-lock" viewBox="0 0 24 24"><path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm-6 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm3.1-9H8.9V6c0-1.71 1.39-3.1 3.1-3.1 1.71 0 3.1 1.39 3.1 3.1v2z"/></symbol><symbol id="i-door" viewBox="0 0 24 24"><path d="M19 19V5c0-1.1-.9-2-2-2H7c-1.1 0-2 .9-2 2v14H3v2h18v-2h-2zm-2 0H7V5h10v14zm-4-8c.55 0 1-.45 1-1s-.45-1-1-1-1 .45-1 1 .45 1 1 1z"/></symbol><symbol id="i-key" viewBox="0 0 24 24"><path d="M12.65 10C11.83 7.67 9.61 6 7 6c-3.31 0-6 2.69-6 6s2.69 6 6 6c2.61 0 4.83-1.67 5.65-4H17v4h4v-4h2v-4H12.65zM7 14c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2z"/></symbol><symbol id="i-tool" viewBox="0 0 24 24"><path d="M22.7 19l-9.1-9.1c.9-2.3.4-5-1.5-6.9-2-2-5-2.4-7.4-1.3L9 6 6 9 1.6 4.7C.4 7.1.9 10.1 2.9 12.1c1.9 1.9 4.6 2.4 6.9 1.5l9.1 9.1c.4.4 1 .4 1.4 0l2.3-2.3c.5-.4.5-1.1.1-1.4z"/></symbol><symbol id="i-home" viewBox="0 0 24 24"><path d="M10 20v-6h4v6h5v-8h3L12 3 2 12h3v8z"/></symbol><symbol id="i-star" viewBox="0 0 24 24"><path d="M12 17.27L18.18 21l-1.64-7.03L22 9.24l-7.19-.61L12 2 9.19 8.63 2 9.24l5.46 4.73L5.82 21z"/></symbol><symbol id="i-location" viewBox="0 0 24 24"><path d="M12 2C8.13 2 5 5.13 5 9c0 5.25 7 13 7 13s7-7.75 7-13c0-3.87-3.13-7-7-7zm0 9.5c-1.38 0-2.5-1.12-2.5-2.5s1.12-2.5 2.5-2.5 2.5 1.12 2.5 2.5-1.12 2.5-2.5 2.5z"/></symbol><symbol id="i-diamond" viewBox="0 0 24 24"><path d="M19 3H5L2 9l10 12L22 9l-3-6zm-9 12.53L5.31 9h13.38L12 15.53z"/></symbol></svg>';
    html += '<div class="top-bar"><div class="top-bar-inner"><div class="top-bar-item"><svg><use href="#i-clock"/></svg> Disponible 24h/24 - 7j/7</div><div class="top-bar-item"><svg><use href="#i-shield"/></svg> Agree assurances</div><div class="top-bar-item"><svg><use href="#i-diamond"/></svg> Service Premium</div></div></div>';
    html += '<header><div class="header-inner"><a href="/" class="logo"><div class="logo-icon"><svg><use href="#i-lock"/></svg></div><div><div class="logo-text">Maison <span>Secure</span></div><div class="logo-sub">L\'excellence en securite</div></div></a><div class="header-contact"><a href="tel:' + TEL_CLEAN + '" class="header-phone"><svg><use href="#i-phone"/></svg> ' + TEL + '</a><a href="#contact" class="btn-rdv">Prendre rendez-vous</a></div></div></header>';
    html += '<section class="hero"><div class="hero-inner"><div class="hero-content"><div class="hero-badge"><svg style="width:16px;height:16px;fill:currentColor"><use href="#i-diamond"/></svg> Service Premium</div><h1>Serrurier <span>' + nom + '</span></h1><p class="hero-subtitle">Decouvrez l\'excellence en serrurerie ' + titreComplet + '. Notre equipe d\'artisans qualifies intervient avec discretion et professionnalisme, 24 heures sur 24.</p><div class="hero-features"><div class="hero-feature"><div class="hero-feature-icon"><svg><use href="#i-clock"/></svg></div><span>Intervention rapide</span></div><div class="hero-feature"><div class="hero-feature-icon"><svg><use href="#i-shield"/></svg></div><span>Garantie 2 ans</span></div><div class="hero-feature"><div class="hero-feature-icon"><svg><use href="#i-diamond"/></svg></div><span>Service premium</span></div></div><div class="hero-buttons"><a href="tel:' + TEL_CLEAN + '" class="btn-primary"><svg><use href="#i-phone"/></svg> Nous appeler</a><a href="#contact" class="btn-secondary">Demander un devis</a></div></div>';
    html += '<div class="trust-box"><div class="trust-box-header"><h3>Votre confiance, notre priorite</h3><div class="trust-rating"><div class="trust-stars"><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg></div><span class="trust-score">4.9/5</span><span class="trust-reviews">(1 847 avis)</span></div></div><div class="trust-features"><div class="trust-feature"><svg><use href="#i-clock"/></svg><div><h4>Disponibilite permanente</h4><p>Service 24h/24, 7j/7</p></div></div><div class="trust-feature"><svg><use href="#i-shield"/></svg><div><h4>Intervention garantie</h4><p>Garantie 2 ans sur toutes prestations</p></div></div><div class="trust-feature"><svg><use href="#i-diamond"/></svg><div><h4>Excellence reconnue</h4><p>Artisans certifies et experimentes</p></div></div></div><div class="trust-cta"><a href="tel:' + TEL_CLEAN + '">' + TEL + '</a><p>Appel gratuit et sans engagement</p></div></div></div></section>';
    html += '<section class="services"><div class="container"><div class="section-header"><div class="section-label">Nos prestations</div><h2>Services de Serrurerie Premium</h2><p>Des solutions sur-mesure pour votre securite</p></div><div class="services-grid"><div class="service-card"><div class="service-icon"><svg><use href="#i-door"/></svg></div><h3>Ouverture de porte</h3><p>Intervention delicate sans degradation. Technique de crochetage fine.</p><span class="service-price">Des 89 EUR</span></div><div class="service-card"><div class="service-icon"><svg><use href="#i-lock"/></svg></div><h3>Serrure haute securite</h3><p>Installation de serrures certifiees A2P. Protection optimale.</p><span class="service-price">Des 189 EUR</span></div><div class="service-card"><div class="service-icon"><svg><use href="#i-shield"/></svg></div><h3>Porte blindee</h3><p>Pose de portes blindees sur-mesure. Securite maximale.</p><span class="service-price">Sur devis</span></div><div class="service-card"><div class="service-icon"><svg><use href="#i-key"/></svg></div><h3>Reproduction de cles</h3><p>Duplication de cles haute securite. Confidentialite garantie.</p><span class="service-price">Des 25 EUR</span></div><div class="service-card"><div class="service-icon"><svg><use href="#i-home"/></svg></div><h3>Securisation complete</h3><p>Audit et renforcement de votre securite. Solutions personnalisees.</p><span class="service-price">Sur devis</span></div><div class="service-card"><div class="service-icon"><svg><use href="#i-tool"/></svg></div><h3>Maintenance</h3><p>Entretien preventif de vos installations.</p><span class="service-price">Des 69 EUR</span></div></div></div></section>';
    html += '<section class="avis"><div class="container"><div class="section-header"><div class="section-label">Temoignages</div><h2>L\'avis de nos clients</h2><p>La satisfaction client au coeur de notre engagement</p></div><div class="avis-grid"><div class="avis-card"><div class="avis-header"><div class="avis-avatar">C</div><div class="avis-info"><h4>Catherine L.</h4><p>' + nom + '</p></div></div><div class="avis-stars"><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg></div><p class="avis-text">"Un service d\'une qualite exceptionnelle. L\'artisan etait ponctuel, discret et tres professionnel. Je recommande vivement."</p></div><div class="avis-card"><div class="avis-header"><div class="avis-avatar">J</div><div class="avis-info"><h4>Jean-Pierre M.</h4><p>' + nom + '</p></div></div><div class="avis-stars"><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg></div><p class="avis-text">"Installation d\'une porte blindee realisee avec soin. Le resultat est parfait, tant sur le plan esthetique que securitaire."</p></div><div class="avis-card"><div class="avis-header"><div class="avis-avatar">A</div><div class="avis-info"><h4>Anne-Sophie D.</h4><p>' + nom + '</p></div></div><div class="avis-stars"><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg><svg><use href="#i-star"/></svg></div><p class="avis-text">"Intervention en pleine nuit suite a une perte de cles. Rapide, efficace et rassurant. Un vrai service premium."</p></div></div></div></section>';
    html += '<section class="contact" id="contact"><div class="container"><div class="section-header"><div class="section-label">Contact</div><h2>Prenez rendez-vous</h2><p>Notre equipe est a votre ecoute</p></div><div class="contact-grid"><div class="contact-info"><h3>A votre <span>service</span></h3><p>Notre equipe d\'artisans serruriers qualifies est disponible pour repondre a toutes vos demandes ' + titreComplet + '.</p><div class="contact-methods"><div class="contact-method"><svg><use href="#i-phone"/></svg><div><h4>Telephone</h4><a href="tel:' + TEL_CLEAN + '">' + TEL + '</a></div></div><div class="contact-method"><svg><use href="#i-clock"/></svg><div><h4>Disponibilite</h4><span>24h/24 - 7j/7 - Jours feries</span></div></div><div class="contact-method"><svg><use href="#i-location"/></svg><div><h4>Zone d\'intervention</h4><span>' + nom + ' et environs</span></div></div></div></div>';
    html += '<div class="form-box"><div id="formContainer"><h3>Demande de devis</h3><p>Reponse sous 2 heures garantie</p><form id="contactForm"><div class="form-row"><div class="form-group"><label>Nom</label><input type="text" id="nom" required placeholder="Votre nom"></div><div class="form-group"><label>Telephone</label><input type="tel" id="telephone" required placeholder="06 12 34 56 78"></div></div><div class="form-group"><label>Adresse</label><input type="text" id="adresse" required placeholder="Adresse d\'intervention"></div><div class="form-group"><label>Type de prestation</label><select id="probleme" required><option value="">Selectionnez</option><option>Ouverture de porte</option><option>Changement de serrure</option><option>Installation porte blindee</option><option>Securisation domicile</option><option>Reproduction de cles</option><option>Autre demande</option></select></div><button type="submit" class="btn-submit">Envoyer ma demande</button></form></div><div class="success-message" id="successMessage"><div class="success-icon"><svg><use href="#i-check"/></svg></div><h4>Demande envoyee</h4><p>Nous vous recontactons dans les 2 heures.</p></div></div></div></div></section>';
    html += '<section class="cta"><div class="container cta-content"><h2>Un projet de securite ?</h2><p>Nos experts sont a votre disposition pour vous conseiller</p><a href="tel:' + TEL_CLEAN + '" class="cta-phone"><svg><use href="#i-phone"/></svg> ' + TEL + '</a></div></section>';
    html += '<footer><div class="container"><p>2025 ' + MARQUE + ' - Serrurier Premium ' + nom + ' - Tous droits reserves</p></div></footer>';
    html += '<a href="tel:' + TEL_CLEAN + '" class="floating-btn"><svg><use href="#i-phone"/></svg></a>';
    html += '<script>var CALLMEBOT_PHONE="33635084014",CALLMEBOT_APIKEY="9990329",LIEU="' + nom + '",MARQUE="' + MARQUE + '";document.getElementById("contactForm").addEventListener("submit",function(e){e.preventDefault();var d={nom:document.getElementById("nom").value,telephone:document.getElementById("telephone").value,adresse:document.getElementById("adresse").value,probleme:document.getElementById("probleme").value};var m="*NOUVEAU CONTACT*%0A%0A*Marque:* "+MARQUE+"%0A*Page:* Serrurier "+LIEU+"%0A*Nom:* "+d.nom+"%0A*Tel:* "+d.telephone+"%0A*Adresse:* "+d.adresse+"%0A*Demande:* "+d.probleme;try{fetch("https://api.callmebot.com/whatsapp.php?phone="+CALLMEBOT_PHONE+"&text="+m+"&apikey="+CALLMEBOT_APIKEY,{method:"GET",mode:"no-cors"})}catch(err){}document.getElementById("formContainer").style.display="none";document.getElementById("successMessage").classList.add("show")});document.querySelectorAll(\'a[href^="#"]\').forEach(function(a){a.addEventListener("click",function(e){e.preventDefault();var t=document.querySelector(this.getAttribute("href"));if(t)t.scrollIntoView({behavior:"smooth"})})});</script>';
    html += '</body></html>';
    return html;
}

export async function onRequest(context) {
    var url = new URL(context.request.url);
    var path = url.pathname;
    var theme = url.searchParams.get("theme") || "sos";
    var match = path.match(/^\/serrurier\/(.+)$/);
    if (!match) {
        return new Response("Page non trouvee", { status: 404, headers: { "Content-Type": "text/html;charset=UTF-8" } });
    }
    var lieu = decodeURIComponent(match[1]);
    var data = await validerLieu(lieu);
    if (!data.valide) {
        var html404 = '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Zone non couverte</title></head><body style="font-family:sans-serif;text-align:center;padding:50px"><h1>Zone non couverte</h1><p>Desole, nous n\'intervenons pas encore dans cette zone.</p><a href="/">Retour accueil</a></body></html>';
        return new Response(html404, { status: 404, headers: { "Content-Type": "text/html;charset=UTF-8" } });
    }
    var html = generateHTML(lieu, data, theme);
    return new Response(html, { status: 200, headers: { "Content-Type": "text/html;charset=UTF-8", "Cache-Control": "public, max-age=3600" } });
}
